[build]
  # Chain multiple commands
  command = "composer install && npm install && npm run build && php artisan serve"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
